# -*- coding: utf-8 -*-
"""Mobile Price.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dz4cESb299owtsnkgYnX940dkbJFK4_x
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv('train.csv')

df.head()

df.shape

df.describe()

df.info()

plt.figure(figsize=(12,6))
sns.heatmap(df.corr())
plt.show()

plt.figure(figsize=(12,6))
sns.barplot(x='price_range' , y ='battery_power' , data=df)
plt.show()

plt.figure(figsize=(14,6))
plt.subplot(1,2,1)
sns.barplot(x='price_range',y='px_height',data=df,palette='Reds')
plt.subplot(1,2,2)
sns.barplot(x='price_range',y='px_width',data=df,palette='Blues')
plt.show()

plt.figure(figsize=(12,6))
sns.barplot(x='price_range' , y='ram' ,data=df)
plt.show()

plt.figure(figsize=(12,6))
sns.countplot(df['three_g'], hue=df['price_range'],palette='pink')
plt.show()

plt.figure(figsize=(12,6))
sns.countplot(df['four_g'], hue=df['price_range'],palette='ocean')
plt.show()

plt.figure(figsize=(12,6))
sns.lineplot(x='price_range', y='int_memory', data=df,hue='dual_sim')
plt.show()

x=df.drop(['price_range'],axis=1)
y=df['price_range']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=0)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(x_train,y_train)

knn.score(x_train,y_train)

